// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "buyfakett",
            "url": "https://github.com/buyfakett"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/config/add": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "创建配置",
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config_info.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.CreateConfigResp"
                        }
                    }
                }
            }
        },
        "/api/config/batch_delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "批量删除配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "批量删除配置",
                "parameters": [
                    {
                        "description": "批量删除请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config_info.BatchDeleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.BatchDeleteConfigResp"
                        }
                    }
                }
            }
        },
        "/api/config/cleanup": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "清理配置旧版本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "清理配置旧版本",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.ConfigCleanupResp"
                        }
                    }
                }
            }
        },
        "/api/config/clone": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据提供的配置项列表进行克隆操作。先用data_id、group_id和tenant_id查询，如果不存在则用config_id查询原配置并插入新配置，version设为1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "克隆配置",
                "parameters": [
                    {
                        "description": "克隆配置请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config_info.CloneReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.ConfigCloneResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/config_info.ConfigCloneResp"
                        }
                    },
                    "401": {
                        "description": "无权限",
                        "schema": {
                            "$ref": "#/definitions/config_info.ConfigCloneResp"
                        }
                    },
                    "404": {
                        "description": "命名空间不存在",
                        "schema": {
                            "$ref": "#/definitions/config_info.ConfigCloneResp"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/config_info.ConfigCloneResp"
                        }
                    }
                }
            }
        },
        "/api/config/delete/{config_id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "删除配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置ID",
                        "name": "config_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.DeleteConfigResp"
                        }
                    }
                }
            }
        },
        "/api/config/get": {
            "get": {
                "description": "通过tenant、dataId、group参数获取配置内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "通过参数获取配置内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "tenant_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "数据ID",
                        "name": "data_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分组ID",
                        "name": "group_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.ContentByParamsResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/config_info.ContentByParamsResp"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "$ref": "#/definitions/config_info.ContentByParamsResp"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/config_info.ContentByParamsResp"
                        }
                    }
                }
            }
        },
        "/api/config/get/{config_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取配置详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "获取配置详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置ID",
                        "name": "config_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.ContentResp"
                        }
                    }
                }
            }
        },
        "/api/config/get_by_file": {
            "get": {
                "description": "获取配置(直接返回配置内容)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "获取配置(直接返回配置内容)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租户",
                        "name": "tenant",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "数据ID",
                        "name": "dataId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分组",
                        "name": "group",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "配置内容",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "head": {
                "description": "获取配置(直接返回配置内容)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "获取配置(直接返回配置内容)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租户",
                        "name": "tenant",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "数据ID",
                        "name": "dataId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分组",
                        "name": "group",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "配置内容",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/get_by_user": {
            "get": {
                "description": "直接使用账号获取配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "直接使用账号获取配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "tenant",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "数据ID",
                        "name": "dataId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分组ID",
                        "name": "group",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "head": {
                "description": "直接使用账号获取配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "直接使用账号获取配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "tenant",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "数据ID",
                        "name": "dataId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分组ID",
                        "name": "group",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/get_version/{config_id}": {
            "get": {
                "description": "通过config_id查询data_id和group_id，然后查询所有不同版本，按版本字段倒序返回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "获取配置的所有版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置ID",
                        "name": "config_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.ListVersionResp"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/config_info.ListVersionResp"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "$ref": "#/definitions/config_info.ListVersionResp"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/config_info.ListVersionResp"
                        }
                    }
                }
            }
        },
        "/api/config/language_list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "配置支持语言列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "配置支持语言列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.LanguageListResp"
                        }
                    }
                }
            }
        },
        "/api/config/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "配置列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "配置列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "命名空间id",
                        "name": "tenant_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "配置id",
                        "name": "data_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "组id",
                        "name": "group_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "类型",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.ListResp"
                        }
                    }
                }
            }
        },
        "/api/config/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "搜索配置内容，返回匹配行及上下文",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "搜索配置内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键字",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间id",
                        "name": "tenant_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.SearchResp"
                        }
                    }
                }
            }
        },
        "/api/config/update/{config_id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "更新配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置ID",
                        "name": "config_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "配置信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config_info.UpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.UpdateConfigResp"
                        }
                    }
                }
            }
        },
        "/api/config/update_by_file": {
            "post": {
                "description": "更新/创建配置(文件上传)",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "更新/创建配置(文件上传)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenant",
                        "name": "tenant",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dataId",
                        "name": "dataId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "group",
                        "name": "group",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "content",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.UpdateConfigByFileResp"
                        }
                    }
                }
            }
        },
        "/api/config/update_by_user": {
            "post": {
                "description": "使用账号更新/创建配置",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置"
                ],
                "summary": "使用账号更新/创建配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant",
                        "name": "tenant",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dataId",
                        "name": "dataId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "group",
                        "name": "group",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "content",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.UpdateConfigByUserResp"
                        }
                    }
                }
            }
        },
        "/api/is_demo": {
            "get": {
                "description": "获取demo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试"
                ],
                "summary": "获取demo",
                "responses": {}
            }
        },
        "/api/metrics": {
            "get": {
                "tags": [
                    "监控"
                ],
                "summary": "普罗米修斯监控",
                "responses": {}
            }
        },
        "/api/permission/add": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "为角色分配权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "创建权限",
                "parameters": [
                    {
                        "description": "权限信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/permission.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/permission.CreatePermissionResp"
                        }
                    }
                }
            }
        },
        "/api/permission/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除角色的指定权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "删除权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色名",
                        "name": "role",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "资源路径",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "操作类型",
                        "name": "action",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/permission.DeletePermissionResp"
                        }
                    }
                }
            }
        },
        "/api/permission/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取角色的权限列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "权限列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色名",
                        "name": "role",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/permission.ListResp"
                        }
                    }
                }
            }
        },
        "/api/ping": {
            "get": {
                "description": "测试网络接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试"
                ],
                "summary": "测试网络接口",
                "responses": {}
            }
        },
        "/api/role/add": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建新的角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "角色信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/role.CreateRoleResp"
                        }
                    }
                }
            }
        },
        "/api/role/delete/{role}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除指定角色及其所有权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色名",
                        "name": "role",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/role.DeleteRoleResp"
                        }
                    }
                }
            }
        },
        "/api/role/edit": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "全量更新角色关联的用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "编辑角色",
                "parameters": [
                    {
                        "description": "编辑请求信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role.EditReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/role.EditRoleResp"
                        }
                    }
                }
            }
        },
        "/api/role/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取所有角色列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "角色列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/role.ListResp"
                        }
                    }
                }
            }
        },
        "/api/server_info": {
            "get": {
                "description": "服务信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试"
                ],
                "summary": "服务信息",
                "responses": {}
            }
        },
        "/api/tenant/add": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建命名空间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "命名空间"
                ],
                "summary": "创建命名空间",
                "parameters": [
                    {
                        "description": "创建命名空间请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tenant.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tenant.CreateTenantResp"
                        }
                    }
                }
            }
        },
        "/api/tenant/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除命名空间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "命名空间"
                ],
                "summary": "删除命名空间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tenant.DeleteTenantResp"
                        }
                    }
                }
            }
        },
        "/api/tenant/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "命名空间列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "命名空间"
                ],
                "summary": "命名空间列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tenant.ListResp"
                        }
                    }
                }
            }
        },
        "/api/user/add": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserResp"
                        }
                    }
                }
            }
        },
        "/api/user/captcha": {
            "get": {
                "description": "生成登录验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "生成验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.CaptchaResp"
                        }
                    }
                }
            }
        },
        "/api/user/change_passwd/{user_id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改用户密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "密码信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangePasswdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.ChangePasswordResp"
                        }
                    }
                }
            }
        },
        "/api/user/delete/{user_id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.DeleteUserResp"
                        }
                    }
                }
            }
        },
        "/api/user/info/{user_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.InfoResp"
                        }
                    }
                }
            }
        },
        "/api/user/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.ListResp"
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录凭证",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.LoginResp"
                        }
                    }
                }
            }
        },
        "/api/user/logout": {
            "post": {
                "description": "用户登出，删除JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.LogoutResp"
                        }
                    }
                }
            }
        },
        "/api/user/sync-ldap": {
            "post": {
                "description": "从LDAP同步所有用户到本地数据库，仅添加本地不存在的用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "同步LDAP用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.SyncLDAPUsersResp"
                        }
                    }
                }
            }
        },
        "/api/user/update/{user_id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "更新用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UpdateUserResp"
                        }
                    }
                }
            }
        },
        "/nacos/v1/auth/login": {
            "post": {
                "description": "用户登录(nacos兼容)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户",
                    "nacos兼容"
                ],
                "summary": "用户登录(nacos兼容)",
                "parameters": [
                    {
                        "description": "登录凭证",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.NacosLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.NacosLoginResp"
                        }
                    }
                }
            }
        },
        "/nacos/v1/cs/configs": {
            "get": {
                "description": "获取配置(nacos兼容)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "配置",
                    "nacos兼容"
                ],
                "summary": "获取配置(nacos兼容)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "accessToken",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant",
                        "name": "tenant",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dataId",
                        "name": "dataId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "group",
                        "name": "group",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "更新/创建配置(nacos兼容)",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置",
                    "nacos兼容"
                ],
                "summary": "更新/创建配置(nacos兼容)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "accessToken",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant",
                        "name": "tenant",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dataId",
                        "name": "dataId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "group",
                        "name": "group",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "content",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config_info.NacosUpdateConfigResp"
                        }
                    }
                }
            },
            "head": {
                "description": "获取配置(nacos兼容)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "配置",
                    "nacos兼容"
                ],
                "summary": "获取配置(nacos兼容)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "accessToken",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant",
                        "name": "tenant",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dataId",
                        "name": "dataId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "group",
                        "name": "group",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config_info.BatchDeleteConfigResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.BatchDeleteReq": {
            "type": "object",
            "required": [
                "config_ids"
            ],
            "properties": {
                "config_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "config_info.CloneItems": {
            "type": "object",
            "required": [
                "config_id",
                "data_id",
                "group_id"
            ],
            "properties": {
                "config_id": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "data_id": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "group_id": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "config_info.CloneReq": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config_info.CloneItems"
                    }
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "config_info.ConfigCleanupResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.ConfigCloneResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.ContentByParamsData": {
            "type": "object",
            "properties": {
                "config_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "data_id": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "config_info.ContentByParamsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "$ref": "#/definitions/config_info.ContentByParamsData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.ContentData": {
            "type": "object",
            "properties": {
                "config_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "data_id": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "config_info.ContentResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "$ref": "#/definitions/config_info.ContentData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.CreateConfigResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.CreateReq": {
            "type": "object",
            "required": [
                "data_id",
                "group_id",
                "tenant_id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "data_id": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "group_id": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "tenant_id": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                },
                "type": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                }
            }
        },
        "config_info.DeleteConfigResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.LanguageListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.ListData": {
            "type": "object",
            "properties": {
                "config_id": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "data_id": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "config_info.ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config_info.ListData"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "config_info.ListVersionData": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "config_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "data_id": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "config_info.ListVersionResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config_info.ListVersionData"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "config_info.NacosUpdateConfigResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.SearchMatch": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "line_no": {
                    "type": "integer"
                }
            }
        },
        "config_info.SearchResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config_info.SearchResultData"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "config_info.SearchResultData": {
            "type": "object",
            "properties": {
                "config_id": {
                    "type": "integer"
                },
                "data_id": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config_info.SearchMatch"
                    }
                },
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "config_info.UpdateConfigByFileResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.UpdateConfigByUserResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.UpdateConfigResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "config_info.UpdateReq": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "data_id": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "group_id": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "type": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "handler.Code": {
            "type": "integer",
            "enum": [
                200,
                400,
                401,
                500,
                501,
                502,
                503,
                504,
                505
            ],
            "x-enum-varnames": [
                "Code_Success",
                "Code_ParamErr",
                "Code_Unauthorized",
                "Code_Err",
                "Code_DBErr",
                "Code_PasswordErr",
                "Code_AlreadyExists",
                "Code_CaptchaErr",
                "Code_UserErr"
            ]
        },
        "permission.CreatePermissionResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "permission.CreateReq": {
            "type": "object",
            "required": [
                "action",
                "resource",
                "role"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "resource": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "role": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "permission.DeletePermissionResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "permission.ListData": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "permission.ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/permission.ListData"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "role.CreateReq": {
            "type": "object",
            "required": [
                "role",
                "usernames"
            ],
            "properties": {
                "role": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "usernames": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "role.CreateRoleResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "role.DeleteRoleResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "role.EditReq": {
            "type": "object",
            "required": [
                "role",
                "usernames"
            ],
            "properties": {
                "role": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "usernames": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "role.EditRoleResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "role.ListData": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                },
                "usernames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "role.ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role.ListData"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "tenant.CreateReq": {
            "type": "object",
            "required": [
                "tenant_desc",
                "tenant_id",
                "tenant_name"
            ],
            "properties": {
                "tenant_desc": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "tenant_id": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "tenant_name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "tenant.CreateTenantResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "tenant.DeleteTenantResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "tenant.ListData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "tenant_desc": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "tenant_name": {
                    "type": "string"
                }
            }
        },
        "tenant.ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tenant.ListData"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "user.CaptchaData": {
            "type": "object",
            "properties": {
                "base64_image": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "user.CaptchaResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "$ref": "#/definitions/user.CaptchaData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "user.ChangePasswdReq": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                }
            }
        },
        "user.ChangePasswordResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "user.CreateReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "user.CreateUserResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "user.DeleteUserResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "user.InfoData": {
            "type": "object",
            "properties": {
                "enable": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.InfoResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "$ref": "#/definitions/user.InfoData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "user.ListData": {
            "type": "object",
            "properties": {
                "enable": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.ListData"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "user.LoginData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "user.LoginReq": {
            "type": "object",
            "required": [
                "captcha",
                "captcha_id",
                "password",
                "username"
            ],
            "properties": {
                "captcha": {
                    "type": "string",
                    "maxLength": 10,
                    "minLength": 1
                },
                "captcha_id": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "remember_me": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "user.LoginResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "data": {
                    "$ref": "#/definitions/user.LoginData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "user.LogoutResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "user.NacosLoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "username": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "user.NacosLoginResp": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "user.SyncLDAPUsersData": {
            "type": "object",
            "properties": {
                "synced_users": {
                    "description": "同步的用户数量",
                    "type": "integer"
                },
                "total_ldap_users": {
                    "description": "LDAP中的总用户数量",
                    "type": "integer"
                }
            }
        },
        "user.SyncLDAPUsersResp": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/handler.Code"
                        }
                    ]
                },
                "data": {
                    "description": "响应数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.SyncLDAPUsersData"
                        }
                    ]
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string"
                }
            }
        },
        "user.UpdateReq": {
            "type": "object",
            "properties": {
                "enable": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "user.UpdateUserResp": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/handler.Code"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
